[versions]
appCompat = "1.3.1"
core = "1.7.0"
coroutines = "1.5.2"
kotest = "4.6.3"
serialization = "1.3.1"

[libraries]
androidx-appcompat-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidx-core-coreKtx = { module = "androidx.core:core-ktx", version.ref = "core" }
jetbrains-kotlin-kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test" }
jetbrains-kotlinx-kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
jetbrains-kotlinx-kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotest-kotestAssertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

[bundles]
testing = ["jetbrains-kotlin-kotlinTest", "kotest-kotestAssertionsCore"]
