[versions]
appCompat = "1.4.1"
core = "1.8.0"
kotest = "5.3.0"
serialization = "1.3.2"

[libraries]
androidx-appcompat-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidx-core-coreKtx = { module = "androidx.core:core-ktx", version.ref = "core" }
jetbrains-kotlin-kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test" }
jetbrains-kotlinx-kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotest-kotestAssertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

[bundles]
testing = ["jetbrains-kotlin-kotlinTest", "kotest-kotestAssertionsCore"]
