name: clear-cache

on: [ workflow_dispatch ]

jobs:
  clear-cache:
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clear cache
        uses: easimon/wipe-cache@v1
